repositories {
    mavenCentral()
    // force gradle to download FastUtil and LWJGL from the central maven so we can get source artifacts
    exclusiveContent { // Force
        forRepository { mavenCentral() }
        filter {
            includeGroup("it.unimi.dsi")
            includeGroup("org.lwjgl")
            includeGroupAndSubgroups("io.netty")
            includeGroup("com.google.guava")
            includeGroup("io.netty")
        }
    }

    exclusiveContent { // GTM, ModularUI
        forRepository { maven { url = "https://maven.gtceu.com/" } }
        filter {
            includeGroup("com.gregtechceu.gtceu")
            includeGroup("brachy.modularui")
        }
    }
    exclusiveContent { // Configuration
        forRepositories(
                maven { url = "https://repo.repsy.io/mvn/toma/public/" },
                maven { url = "https://api.repsy.io/mvn/toma/public/" },
        )
        filter { includeGroup("dev.toma.configuration")}
    }
    exclusiveContent {
        forRepository { maven { url = "https://maven.firstdarkdev.xyz/snapshots/" } }
        filter {
            includeGroup("com.lowdragmc.ldlib")
        }
    }
    exclusiveContent { // Registrate
        forRepository { maven { url = "https://maven.tterrag.com/" } }
        filter { includeGroup("com.tterrag.registrate") }
    }

    exclusiveContent { // JEI, ModernFix
        forRepository { maven { url = "https://maven.blamejared.com/" } }
        filter {
            includeGroup("mezz.jei")
            includeGroup("org.embeddedt")
        }
    }
    exclusiveContent { // JEI mirror, AE2
        forRepository { maven { url = "https://modmaven.dev/" } }
        filter {
            // includeGroup("mezz.jei")
            includeGroup("appeng")
        }
    }

    exclusiveContent { // EMI
        forRepository { maven { url = "https://repo.sleeping.town/" } }
        filter { includeGroup("dev.emi") }
    }

    exclusiveContent { // KubeJS and Rhino
        forRepository { maven { url = "https://maven.latvian.dev/releases/" } }
        filter {
            includeGroup("dev.latvian.mods")
            includeGroup("dev.latvian.apps")
        }
    }
    exclusiveContent { // Architectury (for KJS 1.20)
        forRepository { maven { url = "https://maven.shedaniel.me/" } }
        filter {
            includeGroup("dev.architectury")
        }
    }

    exclusiveContent { // Curios
        forRepository { maven { url = "https://maven.theillusivec4.top/" } }
        filter { includeGroup('top.theillusivec4.curios') }
    }

    exclusiveContent { // Radium
        forRepository { maven { url = "https://repo.constructlegacy.ru/public/" } }
        filter { includeGroup('me.jellysquid.mods') }
    }

    exclusiveContent { // Modrinth Maven
        forRepository { maven { url = "https://api.modrinth.com/maven/" } }
        filter { includeGroup("maven.modrinth") }
    }
    exclusiveContent { // CurseForge Maven
        forRepository { maven { url = "https://cursemaven.com/" } }
        filter { includeGroup("curse.maven") }
    }
}