# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download = false
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.daemon = false
org.gradle.debug = false

# Compilation/Dependency bundling flags
enableJarJarDependencies = true

# Mod Info
mod_id=gcyr
mod_name=Gregicality Rocketry
mod_license = GNU LGPL 3.0
mod_version = 0.2.8
mod_description = A space addon for GTM
mod_authors = Original Developer: screret - Current Developers - JustReclipse NemEzanevem JuiceyBeans - Worldgen Dev: zvoltaic
mod_credits = The Original Idea/Inspration: Advanced Rocketry
mod_url = https://curseforge.com/minecraft/mc-mods/gcyr
mod_issue_tracker = https://github.com/Argent-Matter/gcyr/issues/
maven_group = argent_matter